/**
 * Icon registry — the single icon language for this app.
 *
 * Rules:
 *  - Font Awesome (free solid) is the only icon library. Nothing else may be
 *    imported for iconography.
 *  - One semantic concept maps to exactly one glyph. "maintenance" must look
 *    identical in the sidebar, in a table cell and on a card.
 *  - Only the icons listed here are imported, so the bundle stays scoped.
 *
 * Add a concept here rather than importing a Font Awesome icon directly at a
 * call site — the registry is what keeps the language consistent.
 */
import {
  // navigation / app sections
  faTableColumns,
  faSitemap,
  faCubes,
  faBookBookmark,
  faFlask,
  faArrowTrendUp,
  faArrowTrendDown,
  faCodeCompare,
  faDice,
  faCalendarCheck,
  faWaveSquare,
  faHeartPulse,
  faTrophy,
  faFileLines,
  faLeaf,
  faPlug,
  faBookOpen,
  faSliders,
  faHouse,
  // actions
  faPlay,
  faRightFromBracket,
  faBars,
  faPlus,
  faMinus,
  faTrashCan,
  faCheck,
  faXmark,
  faMagnifyingGlass,
  faFilter,
  faArrowsRotate,
  faEye,
  faEyeSlash,
  faStar,
  faEllipsis,
  faGripVertical,
  faDownload,
  faUpload,
  faArrowUpRightFromSquare,
  // direction
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faCircle,
  faCircleDot,
  // system / status
  faLock,
  faEnvelope,
  faShieldHalved,
  faBan,
  faTriangleExclamation,
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faClock,
  faUsers,
  faBuilding,
  faDatabase,
  faServer,
  faMicrochip,
  faTowerBroadcast,
  faCodeBranch,
  faLayerGroup,
  faBoxOpen,
  faBolt,
  faBell,
  faCalendarDays,
  // automotive / fleet
  faWrench,
  faGasPump,
  faGaugeHigh,
  faDroplet,
  faRecycle,
  faTrain,
  faRoute,
  faMapLocationDot,
  faScrewdriverWrench,
  // data
  faChartLine,
  faChartColumn,
  faChartPie,
  faCalculator,
  faPercent,
  faPiggyBank,
  faTableList,
  faMoneyBillTrendUp,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  /* ---- navigation / app sections ---- */
  dashboard: faTableColumns,
  hierarchy: faSitemap,
  bom: faCubes,
  library: faBookBookmark,
  simulation: faFlask,
  forecasting: faArrowTrendUp,
  scenarios: faCodeCompare,
  monteCarlo: faDice,
  schedule: faCalendarCheck,
  reliability: faWaveSquare,
  assetHealth: faHeartPulse,
  benchmark: faTrophy,
  document: faFileLines,
  sustainability: faLeaf,
  integrations: faPlug,
  glossary: faBookOpen,
  settings: faSliders,
  home: faHouse,

  /* ---- actions ---- */
  play: faPlay,
  logout: faRightFromBracket,
  menu: faBars,
  add: faPlus,
  subtract: faMinus,
  delete: faTrashCan,
  check: faCheck,
  close: faXmark,
  search: faMagnifyingGlass,
  filter: faFilter,
  refresh: faArrowsRotate,
  show: faEye,
  hide: faEyeSlash,
  star: faStar,
  more: faEllipsis,
  drag: faGripVertical,
  download: faDownload,
  upload: faUpload,
  externalLink: faArrowUpRightFromSquare,
  panelLeft: faTableColumns,

  /* ---- direction ---- */
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  circle: faCircle,
  circleDot: faCircleDot,

  /* ---- system / status ---- */
  lock: faLock,
  mail: faEnvelope,
  warrantyActive: faShieldHalved,
  warrantyExpired: faBan,
  warning: faTriangleExclamation,
  info: faCircleInfo,
  success: faCircleCheck,
  error: faCircleExclamation,
  clock: faClock,
  users: faUsers,
  organization: faBuilding,
  database: faDatabase,
  server: faServer,
  cpu: faMicrochip,
  signal: faTowerBroadcast,
  branch: faCodeBranch,
  layers: faLayerGroup,
  package: faBoxOpen,
  power: faBolt,
  notification: faBell,
  calendar: faCalendarDays,

  /* ---- automotive / fleet ---- */
  maintenance: faWrench,
  repair: faScrewdriverWrench,
  fuel: faGasPump,
  gauge: faGaugeHigh,
  fluid: faDroplet,
  recycle: faRecycle,
  locomotive: faTrain,
  route: faRoute,
  map: faMapLocationDot,

  /* ---- data ---- */
  chart: faChartLine,
  chartBar: faChartColumn,
  chartPie: faChartPie,
  calculator: faCalculator,
  percent: faPercent,
  savings: faPiggyBank,
  table: faTableList,
  cost: faMoneyBillTrendUp,
  trendUp: faArrowTrendUp,
  trendDown: faArrowTrendDown,
} as const;

export type IconName = keyof typeof icons;
