/**
 * Icon registry — the single icon language for this app.
 *
 * Rules:
 *  - Font Awesome (free solid) is the primary icon library.
 *  - One semantic concept maps to exactly one glyph. "maintenance" must look
 *    identical in the sidebar, in a table cell and on a card.
 *  - Only the icons listed here are imported, so the bundle stays scoped and tree-shakeable.
 *
 * Add a concept here rather than importing a Font Awesome icon directly at a
 * call site — the registry is what keeps the language consistent.
 */
import {
  // navigation / app sections
  faTableColumns,
  faSitemap,
  faCubes,
  faBookBookmark,
  faFlask,
  faArrowTrendUp,
  faArrowTrendDown,
  faCodeCompare,
  faDice,
  faCalendarCheck,
  faWaveSquare,
  faHeartPulse,
  faTrophy,
  faFileLines,
  faLeaf,
  faPlug,
  faBookOpen,
  faSliders,
  faHouse,
  faCarSide,
  faUser,
  // actions
  faPlay,
  faRightFromBracket,
  faBars,
  faPlus,
  faMinus,
  faTrashCan,
  faCheck,
  faXmark,
  faMagnifyingGlass,
  faFilter,
  faArrowsRotate,
  faEye,
  faEyeSlash,
  faStar,
  faEllipsis,
  faEllipsisVertical,
  faGripVertical,
  faDownload,
  faUpload,
  faArrowUpRightFromSquare,
  faBoxArchive,
  faPenToSquare,
  faLink,
  faSort,
  // direction
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faArrowUp,
  faCircle,
  faCircleDot,
  // system / status
  faLock,
  faEnvelope,
  faShieldHalved,
  faBan,
  faTriangleExclamation,
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faCircleQuestion,
  faClock,
  faUsers,
  faBuilding,
  faDatabase,
  faServer,
  faMicrochip,
  faTowerBroadcast,
  faCodeBranch,
  faLayerGroup,
  faBoxOpen,
  faBolt,
  faBell,
  faCalendarDays,
  faExpand,
  faCrosshairs,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faPalette,
  faWandMagicSparkles,
  faCloud,
  // automotive / fleet
  faWrench,
  faGasPump,
  faGaugeHigh,
  faDroplet,
  faRecycle,
  faTrain,
  faRoute,
  faRoad,
  faMapLocationDot,
  faScrewdriverWrench,
  // data
  faChartLine,
  faChartColumn,
  faChartPie,
  faCalculator,
  faPercent,
  faPiggyBank,
  faTableList,
  faMoneyBillTrendUp,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  /* ---- navigation / app sections ---- */
  dashboard: faTableColumns,
  vehicle: faCarSide,
  vehicles: faCarSide,
  hierarchy: faSitemap,
  bom: faCubes,
  library: faBookBookmark,
  simulation: faFlask,
  forecasting: faArrowTrendUp,
  scenarios: faCodeCompare,
  monteCarlo: faDice,
  schedule: faCalendarCheck,
  reliability: faWaveSquare,
  assetHealth: faHeartPulse,
  benchmark: faTrophy,
  document: faFileLines,
  documents: faFileLines,
  sustainability: faLeaf,
  integrations: faPlug,
  glossary: faBookOpen,
  settings: faSliders,
  home: faHouse,
  user: faUser,

  /* ---- actions ---- */
  play: faPlay,
  logout: faRightFromBracket,
  menu: faBars,
  add: faPlus,
  minus: faMinus,
  subtract: faMinus,
  delete: faTrashCan,
  archive: faBoxArchive,
  edit: faPenToSquare,
  check: faCheck,
  close: faXmark,
  search: faMagnifyingGlass,
  filter: faFilter,
  refresh: faArrowsRotate,
  show: faEye,
  hide: faEyeSlash,
  star: faStar,
  more: faEllipsis,
  moreVertical: faEllipsisVertical,
  drag: faGripVertical,
  download: faDownload,
  upload: faUpload,
  link: faLink,
  externalLink: faArrowUpRightFromSquare,
  panelLeft: faTableColumns,

  /* ---- direction ---- */
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowDown: faArrowDown,
  arrowUp: faArrowUp,
  circle: faCircle,
  circleDot: faCircleDot,

  /* ---- system / status ---- */
  lock: faLock,
  mail: faEnvelope,
  warrantyActive: faShieldHalved,
  warrantyExpired: faBan,
  warning: faTriangleExclamation,
  alerts: faTriangleExclamation,
  info: faCircleInfo,
  success: faCircleCheck,
  error: faCircleExclamation,
  help: faCircleQuestion,
  clock: faClock,
  users: faUsers,
  organization: faBuilding,
  database: faDatabase,
  server: faServer,
  cpu: faMicrochip,
  signal: faTowerBroadcast,
  branch: faCodeBranch,
  layers: faLayerGroup,
  package: faBoxOpen,
  power: faBolt,
  notification: faBell,
  calendar: faCalendarDays,
  fullscreen: faExpand,
  target: faCrosshairs,
  zoomIn: faMagnifyingGlassPlus,
  zoomOut: faMagnifyingGlassMinus,
  palette: faPalette,
  sparkle: faWandMagicSparkles,
  cloud: faCloud,

  /* ---- automotive / fleet ---- */
  maintenance: faWrench,
  tools: faScrewdriverWrench,
  repair: faScrewdriverWrench,
  fuel: faGasPump,
  gauge: faGaugeHigh,
  fluid: faDroplet,
  recycle: faRecycle,
  locomotive: faTrain,
  route: faRoute,
  road: faRoad,
  map: faMapLocationDot,
  location: faMapLocationDot,

  /* ---- data ---- */
  chart: faChartLine,
  chartBar: faChartColumn,
  chartPie: faChartPie,
  calculator: faCalculator,
  percent: faPercent,
  savings: faPiggyBank,
  table: faTableList,
  cost: faMoneyBillTrendUp,
  sort: faSort,
  trend: faArrowTrendUp,
  trendUp: faArrowTrendUp,
  trendDown: faArrowTrendDown,
} as const;

export type IconName = keyof typeof icons;
