/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenderRouteImport } from './routes/tender'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ReliabilityRouteImport } from './routes/reliability'
import { Route as MonteCarloRouteImport } from './routes/monte-carlo'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as FleetExplorerRouteImport } from './routes/fleet-explorer'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as BomRouteImport } from './routes/bom'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as AssetHealthRouteImport } from './routes/asset-health'
import { Route as IndexRouteImport } from './routes/index'

const TenderRoute = TenderRouteImport.update({
  id: '/tender',
  path: '/tender',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliabilityRoute = ReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteCarloRoute = MonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetExplorerRoute = FleetExplorerRouteImport.update({
  id: '/fleet-explorer',
  path: '/fleet-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetHealthRoute = AssetHealthRouteImport.update({
  id: '/asset-health',
  path: '/asset-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset-health': typeof AssetHealthRoute
  '/benchmark': typeof BenchmarkRoute
  '/bom': typeof BomRoute
  '/configure': typeof ConfigureRoute
  '/fleet-explorer': typeof FleetExplorerRoute
  '/forecasting': typeof ForecastingRoute
  '/glossary': typeof GlossaryRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/maintenance': typeof MaintenanceRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/reliability': typeof ReliabilityRoute
  '/scenarios': typeof ScenariosRoute
  '/simulation': typeof SimulationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/tender': typeof TenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-health': typeof AssetHealthRoute
  '/benchmark': typeof BenchmarkRoute
  '/bom': typeof BomRoute
  '/configure': typeof ConfigureRoute
  '/fleet-explorer': typeof FleetExplorerRoute
  '/forecasting': typeof ForecastingRoute
  '/glossary': typeof GlossaryRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/maintenance': typeof MaintenanceRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/reliability': typeof ReliabilityRoute
  '/scenarios': typeof ScenariosRoute
  '/simulation': typeof SimulationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/tender': typeof TenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset-health': typeof AssetHealthRoute
  '/benchmark': typeof BenchmarkRoute
  '/bom': typeof BomRoute
  '/configure': typeof ConfigureRoute
  '/fleet-explorer': typeof FleetExplorerRoute
  '/forecasting': typeof ForecastingRoute
  '/glossary': typeof GlossaryRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/maintenance': typeof MaintenanceRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/reliability': typeof ReliabilityRoute
  '/scenarios': typeof ScenariosRoute
  '/simulation': typeof SimulationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/tender': typeof TenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset-health'
    | '/benchmark'
    | '/bom'
    | '/configure'
    | '/fleet-explorer'
    | '/forecasting'
    | '/glossary'
    | '/integrations'
    | '/library'
    | '/maintenance'
    | '/monte-carlo'
    | '/reliability'
    | '/scenarios'
    | '/simulation'
    | '/sitemap.xml'
    | '/sustainability'
    | '/tender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-health'
    | '/benchmark'
    | '/bom'
    | '/configure'
    | '/fleet-explorer'
    | '/forecasting'
    | '/glossary'
    | '/integrations'
    | '/library'
    | '/maintenance'
    | '/monte-carlo'
    | '/reliability'
    | '/scenarios'
    | '/simulation'
    | '/sitemap.xml'
    | '/sustainability'
    | '/tender'
  id:
    | '__root__'
    | '/'
    | '/asset-health'
    | '/benchmark'
    | '/bom'
    | '/configure'
    | '/fleet-explorer'
    | '/forecasting'
    | '/glossary'
    | '/integrations'
    | '/library'
    | '/maintenance'
    | '/monte-carlo'
    | '/reliability'
    | '/scenarios'
    | '/simulation'
    | '/sitemap.xml'
    | '/sustainability'
    | '/tender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetHealthRoute: typeof AssetHealthRoute
  BenchmarkRoute: typeof BenchmarkRoute
  BomRoute: typeof BomRoute
  ConfigureRoute: typeof ConfigureRoute
  FleetExplorerRoute: typeof FleetExplorerRoute
  ForecastingRoute: typeof ForecastingRoute
  GlossaryRoute: typeof GlossaryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LibraryRoute: typeof LibraryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MonteCarloRoute: typeof MonteCarloRoute
  ReliabilityRoute: typeof ReliabilityRoute
  ScenariosRoute: typeof ScenariosRoute
  SimulationRoute: typeof SimulationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TenderRoute: typeof TenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tender': {
      id: '/tender'
      path: '/tender'
      fullPath: '/tender'
      preLoaderRoute: typeof TenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliability': {
      id: '/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof ReliabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-carlo': {
      id: '/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof MonteCarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-explorer': {
      id: '/fleet-explorer'
      path: '/fleet-explorer'
      fullPath: '/fleet-explorer'
      preLoaderRoute: typeof FleetExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-health': {
      id: '/asset-health'
      path: '/asset-health'
      fullPath: '/asset-health'
      preLoaderRoute: typeof AssetHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetHealthRoute: AssetHealthRoute,
  BenchmarkRoute: BenchmarkRoute,
  BomRoute: BomRoute,
  ConfigureRoute: ConfigureRoute,
  FleetExplorerRoute: FleetExplorerRoute,
  ForecastingRoute: ForecastingRoute,
  GlossaryRoute: GlossaryRoute,
  IntegrationsRoute: IntegrationsRoute,
  LibraryRoute: LibraryRoute,
  MaintenanceRoute: MaintenanceRoute,
  MonteCarloRoute: MonteCarloRoute,
  ReliabilityRoute: ReliabilityRoute,
  ScenariosRoute: ScenariosRoute,
  SimulationRoute: SimulationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustainabilityRoute: SustainabilityRoute,
  TenderRoute: TenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
